### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '3.62'

### ISSUE THREAD

**Issue by realriot** [a-zb/dropfuse#5]
Trying to start dropfuse results in the following error:

python dropfuse.py https://www.dropbox.com/sh/XXXXXXX mnt/
Traceback (most recent call last):
  File "dropfuse.py", line 180, in <module>
    dropfuse = FUSE(DropFuse(link, argv[2]), argv[2],
  File "dropfuse.py", line 85, in **init**
    self.client.parse(s)
  File "dropfuse.py", line 38, in parse
    filesize = self.getSize()
  File "dropfuse.py", line 55, in getSize
    else: return int(num)
ValueError: invalid literal for int() with base 10: '3.62'

Any hints?

**Comment by a-zb** [comment]
> Any hints?
> I'll look into it. Thanks.

**Comment by realriot** [comment]
Any news?

**Comment by a-zb** [comment]
I scheduled it in. I'm looking at it now.

**Comment by a-zb** [comment]
I tried to reproduce it with my shared folder and could not.

Going by the stack trace you provided, I am guessing that you have a 1GB plus
large file and the shared folder shows something along the lines of 3.62 GB on the
page source.

I don't have Gigabyte large files, but I have patched the software to support it.

Although, as it is stated in the README file, current caching method will greedily cache
all files and using this software at the moment on a 3.62 gigabyte file might or might not
work depending on your available RAM. I have not tested it will files of that size.

On the other hand, I have meant to improve caching methods overall so that
it would be safe to use on very large files.

In the end, feel free to try it now with the latest commit: https://github.com/arekzb/dropfuse/commit/ef5fb95c4a0efa303a496b75a9f18c98ce96fa2a

In the meantime, I will work on improving caching methods overall such that large files will not be cached locally.
