### ISSUE TITLE
RunTimeError 1

### ISSUE THREAD

**Issue by kaldown** [a-zb/dropfuse#7]
Hi there.
I just want to install this software on FreeBSD 10, and faced some troubles =(
Already installed FUSE 2.9.3 from SourceForge.net
And have 

```
% pkg info py27-pyquery
py27-pyquery-1.2.6
Name           : py27-pyquery
Version        : 1.2.6
```

%python dropfuse.py https://www.dropbox.com/home/apps/Brace/kaldown.brace.io ~/dbox/

```
loading cache
fuse: failed to open fuse device: No such file or directory
Traceback (most recent call last):
  File "dropfuse.py", line 182, in <module>
    foreground=True, nothreads=True)
  File "/usr/home/kaldown/dropfuse/fuse.py", line 290, in __init__
    raise RuntimeError(err)
RuntimeError: 1
```

Thanks.

**Comment by a-zb** [comment]
Does it happen if you use a superuser account as well ?

Accepted.

I'll need to install a BSD box on a vm to test it out.

thanks,

**Comment by kaldown** [comment]
Yes, it's not working even with %sudo
